import { type FC, useState } from 'react';
import { UserFieldMap } from '../store/types';
import { useForm, Controller } from 'react-hook-form';
import '../../css/main.css';
interface UpdateUserModalProps {
    fieldName: string;
    label: string;
    initialValue: string | number | Date;
    onClose: () => void;
    onSave: (value: string) => void;
}
interface FormData {
    value: string;
}

//^ to complete logic for coef and diet_id i need logic created by Matvii to fetch coef and diets
const UpdateUserModal: FC<UpdateUserModalProps> = ({ fieldName, label, initialValue, onClose, onSave }) => {
    const {
        control,
        handleSubmit,
        formState: { errors },
    } = useForm<FormData>({
        defaultValues: {
            value: initialValue.toString(),
        },
    });

    const onSubmit = (data: FormData) => {
        console.log(data);
        onSave(data.value);
    };
    const getValidationRules = () => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const rules: any = { required: `${label} is required` };

        switch (fieldName) {
            case UserFieldMap.email:
                rules.pattern = {
                    value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                    message: 'Invalid email address',
                };
                break;
            case UserFieldMap.weight:
                rules.min = { value: 10, message: 'Weight must be at least 10 kg' };
                rules.max = { value: 500, message: 'Weight must be less than 500 kg' };
                rules.pattern = {
                    value: /^\d+(\.\d{1,2})?$/,
                    message: 'Please enter a valid weight',
                };
                break;
            case UserFieldMap.height:
                rules.min = { value: 50, message: 'Height must be at least 50 cm' };
                rules.max = { value: 300, message: 'Height must be less than 300 cm' };
                rules.pattern = {
                    value: /^\d+(\.\d{1,2})?$/,
                    message: 'Please enter a valid height',
                };
                break;
            case UserFieldMap.age:
                rules.validate = (value: string) => {
                    const birthDate = new Date(value);
                    const today = new Date();
                    const age = today.getFullYear() - birthDate.getFullYear();
                    if (age < 4) return 'You must be at least 4 years old';
                    if (age > 120) return 'Please enter a valid date of birth';
                    return true;
                };
                break;
            case UserFieldMap.caloriesStandard:
                rules.min = { value: 0, message: 'Calories can not be negative' };
                rules.max = { value: 10000, message: 'Calories must be less than 10000' };
                break;
            default:
                break;
        }

        return rules;
    };

    const [value, setValue] = useState(initialValue.toString());
    let fieldType: string = 'text';
    switch (fieldName) {
        case UserFieldMap.email:
            fieldType = 'email';
            break;
        case UserFieldMap.age:
            fieldType = 'date';
            break;
        case UserFieldMap.weight:
        case UserFieldMap.height:
            fieldType = 'number';
            break;
        default:
            break;
    }

    //! del(only using for testing) change on fetch
    const Diets = [
        { id: 1, name: 'usual diet' },
        { id: 2, name: 'gain weight' },
        { id: 3, name: 'loose diet' },
        { id: 4, name: 'more carbs' },
    ];
    const ActivityCoefs = [
        { id: 1, name: 'Coach potato' },
        { id: 2, name: 'moderate activity' },
        { id: 3, name: 'active' },
        { id: 4, name: 'too active' },
    ];
    //!=============================
    return (
        <div className="modal-overlay">
            <div className="modal">
                <h2>Edit {label}</h2>
                {/*value - must be id getted from fetch + this must be generated by map ,
                        description must be also getted from fetch
                    */}
                <form onSubmit={handleSubmit(onSubmit)}>
                    {fieldName === UserFieldMap.activityCoefId || fieldName === UserFieldMap.dietId ? (
                        <Controller
                            name="value"
                            control={control}
                            rules={getValidationRules()}
                            render={({ field }) => (
                                <select {...field} className={errors.value ? 'modal-input error' : 'modal-input'}>
                                    {fieldName === UserFieldMap.activityCoefId
                                        ? ActivityCoefs.map(el => (
                                              <option key={el.id} value={el.id}>
                                                  {el.name}
                                              </option>
                                          ))
                                        : Diets.map(el => (
                                              <option key={el.id} value={el.id}>
                                                  {el.name}
                                              </option>
                                          ))}
                                </select>
                            )}
                        />
                    ) : (
                        <Controller
                            name="value"
                            control={control}
                            rules={getValidationRules()}
                            render={({ field }) => (
                                <input {...field} type={fieldType} className={errors.value ? 'modal-input error' : 'modal-input'} />
                            )}
                        />
                    )}

                    {errors.value && <span className="error-message">{errors.value.message}</span>}

                    <div className="modal-actions">
                        <button type="button" onClick={onClose} className="btn-cancel">
                            Cancel
                        </button>
                        <button type="submit" className="btn-save">
                            Save
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default UpdateUserModal;
