import { type FC, useState } from 'react';
import { UserFieldMap } from '../store/types';
interface UpdateUserModalProps {
    fieldName: string;
    label: string;
    initialValue: string | number | Date;
    onClose: () => void;
    onSave: (value: string) => void;
}
//^ to complete logic for coef and diet_id i need logic created by Matvii to fetch coef and diets
const UpdateUserModal: FC<UpdateUserModalProps> = ({ fieldName, label, initialValue, onClose, onSave }) => {
    const [value, setValue] = useState(initialValue.toString());
    let fieldType: string = 'text';
    switch (fieldName) {
        case UserFieldMap.email:
            fieldType = 'email';
            break;
        case UserFieldMap.age:
            fieldType = 'date';
            break;
        case UserFieldMap.weight:
        case UserFieldMap.height:
            fieldType = 'number';
            break;
        default:
            break;
    }

    //! del(only using for testing) change on fetch
    const Diets = [
        { id: 1, name: 'usual diet' },
        { id: 2, name: 'gain weight' },
        { id: 3, name: 'loose diet' },
        { id: 4, name: 'more carbs' },
    ];
    const ActivityCoefs = [
        { id: 1, name: 'Coach potato' },
        { id: 2, name: 'moderate activity' },
        { id: 3, name: 'active' },
        { id: 4, name: 'too active' },
    ];
    //!=============================
    return (
        <div className="modal-overlay">
            <div className="modal">
                <h2>Edit {label}</h2>
                {/*value - must be id getted from fetch + this must be generated by map ,
                        description must be also getted from fetch
                    */}
                {fieldName === UserFieldMap.activityCoefId || fieldName === UserFieldMap.dietId ? (
                    <select value={value} onChange={e => setValue(e.target.value)}>
                        {fieldName === UserFieldMap.activityCoefId
                            ? ActivityCoefs.map(el => (
                                  <option key={el.id} value={el.id}>
                                      {el.name}
                                  </option>
                              ))
                            : Diets.map(el => (
                                  <option key={el.id} value={el.id}>
                                      {el.name}
                                  </option>
                              ))}
                    </select>
                ) : (
                    <input type={fieldType} value={value} onChange={e => setValue(e.target.value)} className="modal-input" />
                )}

                <div className="modal-actions">
                    <button onClick={onClose} className="btn-cancel">
                        Cancel
                    </button>
                    <button onClick={() => onSave(value)} className="btn-save">
                        Save
                    </button>
                </div>
            </div>
        </div>
    );
};

export default UpdateUserModal;
